# Site settings
title: Scientist Network for Advancing Policy
nick: SNAP
email: snapscipolorg@gmail.com
description: SNAP Coalition Website
baseurl: ""
url: "https://snapcoalition.org"
google_analytics_4: G-KXSXHFN9B7

# Footer info
affiliation: >
  <b><i>Inspiring and engaging our fellow scientists for meaningful change.</i></b>

contact: >
  <a href="mailto:snapscipolorg@gmail.com" target="_blank"><i class="fa-solid fa-envelope fa-1x"></i> <b>Send SNAP an Email</b></a> <br/>
  <a href="https://docs.google.com/forms/d/e/1FAIpQLSclm6qDeLHbwRk4QPuZR34x77xx5dlKz3tHuHitBdWAiWe5vg/viewform?usp=header"><i class="fa-solid fa-link fa-1x"></i> <b>Join our Mailing List</b></a>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: initiatives
  - name: press
  - name: courses
  - name: team
  - name: news
  - name: blog
# The "Get Involved!" button can be edited in the header file

include:
  - .htaccess
  - _pages

# These settings control the types of collections used by the template
collections:
  initiatives:
    output: true
    permalink: /:collection/:path/
  news:
    output: true
    permalink: /:collection/:path/
  blog:
    output: true
    permalink: /:collection/:path/

# These settings control how pages and collections are included in the site
defaults:
  # _initiatives
  - scope:
      path: ""
      type: initiatives
    values:
      layout: post
  # _news
  - scope:
      path: ""
      type: news
    values:
      layout: post
  # _posts
  - scope:
      path: ""
      type: blog
    values:
      layout: post
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: gridlay

# These settings control the possible categories and their headings for each collection
initiatives_category:
  current:
    title: 'Current Initiatives'
  past:
    title: 'Past Initiatives'
  upcoming:
    title: 'Upcoming Initiatives'

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins: ["jekyll/scholar"]

scholar:
  last_name: Doe
  first_name: [John]

  style: citesty
  locale: en

  source: /assets/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - tags
